name: Release
on:
  create:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Set up GO
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go
      - name: set up dep
        run: |
          export GOBIN=${GOROOT}/bin
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - name: Set GOPATH
        run: |
          echo "##[set-env name=GOPATH;]$(dirname `pwd`)"
          echo "##[add-path]$(dirname `pwd`)/bin"
        shell: bash
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: src/github.com/controlplaneio/kubesec/
      - name: Launch goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
